version: '3.4'

services:
  mongo_incidents:
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27018"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


  incimanager:
    build:
      context: .
    image: incimanager_i2b
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - mongo_incidents
      - agents

  incidashboard:
    build:
      context: ../InciDashboard_i2b
    image: incidashboard_i2b
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - mongo_incidents
      - agents

  mongo_agents:
    image: mongo
    command: mongod --port 27017
    ports:
      - "27017:27017"

  agents:
    build:
      context: ../Agents_i2b
    image: agents_i2b
    ports:
      - "8080:8080"
    depends_on:
      - mongo_agents      

